# Generated by Django 4.0.5 on 2022-06-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Review',
        ),
    ]
