# Generated by Django 4.0.5 on 2022-06-30 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_rename_movie_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='critic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='critic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='recomendation',
            field=models.CharField(choices=[('MW', 'Must Watch'), ('SW', 'Should Watch'), ('AW', 'Avoid Watch'), ('NO', 'No Opinion')], default='NO', max_length=50),
        ),
    ]
