# Generated by Django 4.0.5 on 2022-06-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_rename_start_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recomendation',
            field=models.CharField(choices=[('Must Watch', 'MW'), ('SW', 'Should Watch'), ('AW', 'Avoid Watch'), ('No Opinion', 'NO')], default='No Opinion', max_length=50),
        ),
    ]
