# Generated by Django 4.0.5 on 2022-06-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_created_at_user_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='update_at',
        ),
    ]
